env: gfootball

env_args:
  scenario: 11_vs_11_stochastic
  game_visibility: full
  episode_limit: 3000
  observation_reference_frame: fixed
  representation: "ego_simple119"
  full_obs: False
  view_angle: 160
  rewards: "scoring"
  write_full_episode_dumps: False
  write_video: False
  dump_frequency: 1
  logdir: "episode_dumps"
  move_goalkeeper: False
  env_difficulty: -1
  action_set: "default"

test_nepisode: 32
test_interval: 10000
log_interval: 2000
runner_log_interval: 2000
learner_log_interval: 2000
t_max: 2000000
buffer_cpu_only: True
