env: gfootball

env_args:
  scenario: 11_vs_11_stochastic
  game_visibility: full
  episode_limit: 3000
  observation_reference_frame: fixed
  representation: "ma_po_list"

test_nepisode: 32
test_interval: 10000
log_interval: 2000
runner_log_interval: 2000
learner_log_interval: 2000
t_max: 2000000
buffer_cpu_only: True
